### ISSUE TITLE
Issues with relationship sentence

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#1166]
See: http://localhost:8787/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2032

Some names are not showing up.

**Comment by wsalesky** [comment]
This is because the get-related.xqm uses titles, some of these do not have an english name in the title. Example: http://syriaca.org/person/2032/tei

```
<title level="a" xml:lang="en">
—
<foreign xml:lang="syr">ܩܫܝܫ</foreign>
</title>
```

The title for the HTML page is constructed by grabbing the english headword. This may slow down the name script. Needs testing.

**Comment by wsalesky** [comment]
Fixed. (Ish)

**Comment by dlschwartz** [comment]
@wsalesky I reopened this because I think this might be a data problem and not a problem that the app needs to address. I don't think there should be any persons who lack a syriaca-headword with an xml:lang="en". @davidamichelson and @jsaintlauren can you weigh in on this. The example Winona sites is a saint. I think we need to offer at least a transliteration of the Syriac if not some other standard Anglicized name variant. A syriaca-headword does not need to be sourced to a bibliographic item, it can simply have a @resp attribute indicating that syriaca.org is the responsible party.

**Comment by wsalesky** [comment]
@dlschwartz The records (or at least the few I checked) do have an en-gedsh xml:lang tag, but no English headword in the title. The lack of an English headword in the titleStmt was tripping up the script. (Just as a clarification.)

**Comment by dlschwartz** [comment]
@wsalesky that's what I thought. I believe it is the case that every SBD record must have a `<persName xml:lang="en" syriaca-tags="#syriaca-headword"/>` and every Gazetteer record must have a `<placeName xml:lang="en" syriaca-tags="#syriaca-headword"/>`. Other xml:lang values are optional but this data must appear in every record as far as I'm aware. Those lacking it need to have it added. @davidamichelson and @jsaintlauren should weigh in on this though.

**Comment by dlschwartz** [comment]
@wsalesky once https://github.com/srophe/srophe-app-data/issues/783 is implemented, tested, and ready to be merged into dev, we will need to do the following:

Remove the auto-generated text and replace it with the hard-coded text.

Also, we are currently generating a relationship when a relation element appears in an event factoid, [example](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-504). I have added the needed desc elements by hand. However, we will need to stop auto-generating this text as well and replace it with the hard-coded text.

**Comment by wsalesky** [comment]
@dlschwartz I think this can be closed, correct?
