### ISSUE TITLE
Sorting of XML files by Module - Lower priority

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#420]
This sorting is currently done based on an ana attribute:
```<text><body><bibl xml:id="work-297" ana="#hagiographic">```
and
```<text><body><listPerson><person xml:id="person-13" ana="#syriaca-author #syriaca-saint">```

Instead, let's move to sorting these based on the presence of title elements in the header.

Thus for a record that has the following:
```<TEI xml:lang="en"><teiHeader><fileDesc><titleStmt><title level="m">Qadishe: A Guide to the Syriac Saints</title><title level="s">Gateway to the Syriac Saints</title><title level="s">The Syriac Biographical Dictionary</title>```

Would appear both in Saint's Persons and SBD.

Note, I found some problems in the records related to the series, so we do need to update them first.

**Comment by wsalesky** [comment]
@davidamichelson  
Will manuscripts eventually have a title[@level='m'] or [@level='s'] as well? (I would prefer this from a code consistency point of view, and can add it programmatically if you like.)
Thanks!

**Comment by tacarlson** [comment]
These attributes were originally included in the `<person>` element so that multiple person records could be serialized into a single file, if desired.  Moving it to `<title>` elements would mean that multiple person records could be serialized into a single file with loss of project-relevance specifications, or only within projects.  That may be worth it.  (I don't have a preference; I'm just bringing back this consideration from the past.)

**Comment by wsalesky** [comment]
Thanks @tacarlson. @davidamichelson can talk about it at the meeting tomorrow?

**Comment by wsalesky** [comment]
Current changes only made to codebase, not data.
