### ISSUE TITLE
Search for "zora" should return http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1823

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#518]
Search returns no results (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=zora). Not sure why diacritics are not being ignored in this case. Shouldn't "zora" match "Zʾōrā"?

**Comment by wsalesky** [comment]
The bug is the half ring character. 
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=Z%CA%BEora

We have to run the name normalization scripts on the new names, the lucene filter we have does not handle the half ring characters. I will run that in the next day or so. Clearly I also need to get some automated scripts running as well... I will put it on the list! Thanks.
