### ISSUE TITLE
Syriaca.org Logo

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#527]
Hi Winona,

Would you mind, please, making a large size version of our logo (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/$app-root/resources/img/syriaca-logo.png)? I would like to use it here: http://heritage-at-scale.info/

Thanks,
DM

**Comment by wsalesky** [comment]
How is this?
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/%24app-root/resources/img/icons-syriaca-lg.png
Also here:
https://github.com/srophe/srophe-eXist-app/blob/master/srophe-app/resources/img/icons-syriaca-lg.png

**Comment by nathangibson** [comment]
While we’re at it — are the Syriaca.org <http://syriaca.org/> and resource logos and header images optimized for retina displays? Just checking since they look less than sharp for me — not saying you need to do something about this now. 

I realize I have just publicly declared my elitism on Github.

**Comment by wsalesky** [comment]
I think we can open a new issue for this. I think we talked about it at one point... but do not remember implementing it.
