### ISSUE TITLE
Display issue with works. XSLT

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#541]
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/669

**Comment by wsalesky** [comment]
Actually more of a data problem. Lang is coded into html according to xml:lang tag, in this case there is an Arabic lang tag, but English text. We could not specify the language, but may get some issues with inline bi-directional text display.

**Comment by nathangibson** [comment]
FWIW, I agree it is a problem that we are labeling English text with xml:lang='ar' just because it is an Arabic text. Just thinking out loud here ... 

I suppose we should be doing something more like 
`<note type="ancientVersion">
 <bibl xml:id="bib669-5" source="#bib669-1">
  <textLang mainLang="ar"/>
  cf. <title>CPG</title>
 </bibl>
<bibl xml:id="bib669-7" source="#bib669-1"><textLang mainLang="ka"/>cf. <title>CPG</title></bibl>
...
</note>`
Not sure how easy it would be to redo these ancient versions & modern translations in that format and adjust the XSLT accordingly. 

Alternatively, we could put 
`<note type="ancientVersion" source="#bib669-1"><lang>ar</lang><bibl xml:id="bib669-5">...`
but the <lang> tag is really intended more for dictionaries. 

Any thoughts @davidamichelson?

**Comment by wsalesky** [comment]
I like the lang element option. Based purely on my programer point of view, the xml:lang attribute should specify the language of the actual content of the tag.

**Comment by nathangibson** [comment]
@wsalesky @davidamichelson A further complication:
How do we mark up cases where there is a modern translation of an ancient version. E.g., work/1044#bib1044-15. This is a Latin translation of an ancient Armenian version. If we were purists, we would want to show that this is a bibliographic citation in **French** of a **Latin** translation of an **Armenian** version. 

One possibility would be to include `<lang>hy</lang>` in the note, tag the bibl with `xml:lang="fr"`, and put `<textLang mainLang="la"/>` inside the bibl.

**Comment by nathangibson** [comment]
We want the values of `//note[@type="ancientVersion" or @type="modernTranslation"]/@xml:lang` to be put as first child of note.

**Comment by davidamichelson** [comment]
So please change this:
```
<note xml:lang="hy" type="ancientVersion" source="#bib1044-1"><bibl xml:id="bib1044-15"><editor>trad. latine de P. Peeters</editor><title>AB 28
                (1909)</title><ptr target="http://syriaca.org/bibl/2076"/><citedRange unit="pp">49</citedRange></bibl>```
to
```
<note type="ancientVersion" source="#bib1044-1"><lang>hy</lang><bibl xml:id="bib1044-15"><editor>trad. latine de P. Peeters</editor><title>AB 28
                (1909)</title><ptr target="http://syriaca.org/bibl/2076"/><citedRange unit="pp">49</citedRange></bibl>```

**Comment by davidamichelson** [comment]
Please rework the xslt to achieve the same HTML as we now have.

**Comment by wsalesky** [comment]
Updated the data.
