### ISSUE TITLE
Change to how we visualize names for Anonymous authors

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#559]
Let's clarify tomorrow.

```Anonymous names standard -- Add a new  “Anonymous/Anonymi” + URI as a new name and headword: <persName xml:lang="en" syriaca-tags="#syriaca-headword">Anonymous {URI}</persName>
Add: <trait xml:lang="en">anonymous</trait> after </state>
Standardize the descriptive name as <persName xml:lang="en" source="#bib2235-4" syriaca-tags="#anonymous-description”>The bishop of Nicopolis who survived the earthquake in 498/9</persName>```

**Comment by davidamichelson** [comment]
Keep Anonymi +d format of name but change it to match the URI number
Use the long name in place of the Syriac name
In graphs and visualizations, we will use a shorter name (Anonymous or Anonymi)
E.g., “Anonymous 24 — A virgin who fell and then repented”

**Comment by davidamichelson** [comment]
Solution, we will change the data to put this in the title title stmt and it should show up that way.

**Comment by nathangibson** [comment]
@wsalesky We have changed a bunch of anonymous record titles to have the above format in the title. E.g., for http://wwwb.library.vanderbilt.edu/person/1745 we have the record title "Anonymi 1745 — The two brothers from a monastery in Persia". But the header at the top of the page is displaying  "Anonymi" + URI number + Syriac headword instead of "Anonymi" + URI number + anonymous description. So you could either visualize the record title or use `persName[matches(@syriaca-tags,'#anonymous-description)]` when it exists in place of the Syriac headword, whichever is easier.
