### ISSUE TITLE
Visualize relation for possibly identical

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#570]
We are not currently visualizing this relation:
```<relation name="possibly-identical" mutual="http://syriaca.org/person/2747 http://syriaca.org/person/2748"><desc xml:lang="en">This person is possibly identical
                                                with one or more persons represented in another
                                                record</desc></relation>```
Will this happen when we give you a full list of relations or should we tweak it now?

**Comment by nathangibson** [comment]
I think a long time ago we had discussed possibly visualizing this in or near the identity section, since it relates to disambiguation (also `relation[@name='different-from']`). Also note that eventually we want to prefix all of these relation names with “syriaca:” and will probably want to move them from `@name` to `@ref` to conform to common TEI-LOD practice. Just noting these things so that you’re aware this is a moving target. (Or should we switch these over before having you do the visualization?)

**Comment by wsalesky** [comment]
First pass:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2747

Need to eliminate reference to current record, and capitalize relationship. Add any other bugs or wish list items for this feature here.

**Comment by davidamichelson** [comment]
Hmm, I am not getting anything to show on this record.

**Comment by wsalesky** [comment]
I see it on the dev server. Can you do a hard refresh?

**Comment by davidamichelson** [comment]
You are right, it is there now. Great work! Please change the label to
Capital Case: "Possibly Identical"

**Comment by wsalesky** [comment]
Another bug: List @name only once. 
See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1016
possibly identical possibly identical 

Also make name of relationship more distinct.
