### ISSUE TITLE
Please add the corrections/revisions and is this record complete buttons to all modules

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#767]

**Comment by davidamichelson** [comment]
Please add a record status button next to these. This button should read:

"Status: [Under Review]" or "[Draft]"

Or leave button off if that status = "published"

**Comment by nathangibson** [comment]
https://github.com/srophe/srophe-eXist-app/issues/744

**Comment by wsalesky** [comment]
Testing on persons:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/11

We can make the 'Status' button more attractive, later.

**Comment by davidamichelson** [comment]
I will provide this text.

**Comment by wsalesky** [comment]
Change Status 'btn' to 'badge' add to all modules

**Comment by nathangibson** [comment]
Can't tell if Corrections/Additions button is actually sending an email. The pop-up doesn't close or give any status message. 
This should not be fixed today if there's any risk of it messing up anything else on production, but maybe soon so that people can respond to our plea to start submitting corrections.
