### ISSUE TITLE
Revising How to Cite This Entry

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#810]
After discussion in a weekly meeting it has been recommended that perhaps we should simplify the citation style for each module.

Please see the proposed "How to Cite This Entry" styles and let me know if you have any revisions or objections. 

In general these citations are meant to follow Chicago style "Documentation I: Notes and Bibliography" format based on the section: "14.248 Dictionaries and encyclopedias online": http://www.chicagomanualofstyle.org/16/ch14/ch14_sec248.html

Here are the Chicago examples for bibliography style, of which the third is most similar to us:
- Baldwin, Olive, and Thelma Wilson. “Ann Catley (1745–1789).” In _Oxford Dictionary of National Biography_. Oxford University Press, 2004–. Accessed October 8, 2009. doi:10.1093/ref:odnb/4895.
- Isaacson, Melissa. “Bulls.” In _Encyclopedia of Chicago_, edited by Janice L. Reiff, Ann Durkin Keating, and James R. Grossman. Chicago Historical Society, 2005. http://www.encyclopedia.chicagohistory.org/pages/184.html.
- Masolo, Dismas. “African Sage Philosophy.” In _Stanford Encyclopedia of Philosophy_. Stanford University, 1997–. Article published February 14, 2006. http://plato.stanford.edu.proxy.library.vanderbilt.edu/entries/african-sage/.

For footnote style, we have a choice about how much publication information to add. Chicago explains that: "Well-known online reference works, such as major dictionaries and encyclopedias, are normally cited, like their printed counterparts, in notes rather than in bibliographies. The facts of publication are often omitted, but signed entries may include the name of the author." I don't know if that is us ;)

Here is the model:
- 2. _Grove Music Online_, s.v. “Toscanini, Arturo,” by David Cairns, accessed July 19, 2008, http://www.oxfordmusiconline.com.proxy.library.vanderbilt.edu/. 

Elsewhere though it says that another model for reference articles can be the contribution to a multi-volume book:
- 1. Anne Carr and Douglas J. Schuurman, “Religion and Feminism: A Reformist Christian Analysis,” in _Religion, Feminism, and the Family_, ed. Anne Carr and Mary Stewart Van Leeuwen (Louisville, KY: Westminster John Knox Press, 1996), 14.

On the other hand with regard to online resources, Chicago is fairly insistent about the importance of noting the "authority" or publisher. Chicago is fairly strict on this:  "Electronic content presented without formal ties to a publisher or sponsoring body has the authority equivalent to that of unpublished or self-published material in other media. " (http://www.chicagomanualofstyle.org/16/ch14/ch14_sec009.html)

So that makes me wonder if we do need to still include Syriaca.org or maybe even Vanderbilt in the listing (similar to the Stanford Encyclopedia of Philosophy?

One final consideration, it appears that the Chicago Manual now prefers a "Last Modified" date or a publication date over an "Accessed Date". This should be easy to achieve for us based on the change log.

Anyway here are some revised citations to consider, please comment below.
### Footnote:

**Option 1: Simplex** 
- Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, ed. Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson, last modified August 17, 2016, http://syriaca.org/person/779.

**Option 2: With Syriaca.org as Publisher and Date** 
- Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, ed. Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson (Syriaca.org, 2016-), last modified August 17, 2016, http://syriaca.org/person/779.

**Option 3: With Syriaca.org and Vanderbilt as Publisher and Date** 
- Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, ed. Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson (Syriaca.org & Vanderbilt University, 2016-), last modified August 17, 2016, http://syriaca.org/person/779.

**Option 4: With Vanderbilt as Publisher and Date** 
- Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, ed. Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson (Vanderbilt University, 2016-), last modified August 17, 2016, http://syriaca.org/person/779.

**Option 5: With SBD as Multivolume Work & Vanderbilt as Publisher and Date** 
- Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, ed. Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson, vol. 1 of _The Syriac Biographical Dictionary_ (Vanderbilt University, 2016-), last modified August 17, 2016, http://syriaca.org/person/779.
### Bibliography:

**Option 1: Simplex** 
- Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Entry published August 17, 2016. http://syriaca.org/person/779.

**Option 2: With Syriaca.org as Publisher and Date** 
- Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Syriaca.org, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

**Option 3: With Syriaca.org and Vanderbilt as Publisher and Date** 
- Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Syriaca.org & Vanderbilt University, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

**Option 4: With Vanderbilt as Publisher and Date** 
- Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Vanderbilt University, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

**Option 5: With SBD as Multivolume Work & Vanderbilt as Publisher and Date** 
- Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Vol. 1 of _The Syriac Biographical Dictionary_, edited by David A. Michelson et al. Vanderbilt University, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

**Comment by davidamichelson** [comment]
@srophe/issues-only Dear Colleagues, please weigh in on this and let us know what you prefer. Cliff I have added you since we would appreciate a librarian's thoughts.

Thanks, DM

**Comment by jedwardwalters** [comment]
Given the issues you've outlined, I think option 4 strikes a balance between the most information and the most streamlined. My preference would be the shorter options (1 or 2), but perhaps that's because I just lectured on text criticism and I'm thinking of "the shorter reading is to be preferred." But the issue of a publishing body as authority makes sense. In which case, it seems to me that including Vanderbilt (but not syriaca.org, because that does not seem to add anything to me) achieves that goal. The final option may be too much info, and thus confusing to users (if our goal is simplification).

Those are just my brief thoughts. Interested to hear what others think.

**Comment by nathangibson** [comment]
Wow, it's amazing how many factors there are in a citation! 

For footnotes, my vote is for **Option 3**.

For bibliography, my vote is for 
**Option 3 + SBD as series + all names + "Last modified"**
- Mellon Saint-Laurent, Jeanne-Nicole, David A. Michelson, Nathan P. Gibson, James E. Walters, and Thomas A. Carlson. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. The Syriac Biographical Dictionary, edited by David A. Michelson, Jeanne-Nicole Mellon Saint-Laurent, Nathan P. Gibson, and Daniel L. Schwartz, vol. 1. Syriaca.org & Vanderbilt University, 2016-. Last modified August 17, 2016. http://syriaca.org/person/779.

Here's what I'm thinking: 

1. My general inclination is that the footnote should be relatively short and sweet but the biblio should have as complete information as possible. The reason for this is that footnotes need to be brief (that's their _sitz im leben_) while the bibliography is how the publication titles and academic credit will be propagated in traditional media. So we shouldn't shortchange that.

2. On a related note, the way I read the Chicago Manual, we should include up to 2-3 authors/editors in footnotes, but up to 10 in bibliography (www.chicagomanualofstyle.org/16/ch14/ch14_sec076.html). I'd vote for limiting it to 2 for footnotes to keep it short. I realize that the above bibliography entry is very long, but since we've been making such a point of giving academic credit where it's due so that digital work can be properly acknowledged, it'd be a shame to throw that away by not including it in the most standard form of recognition.

2. I think "Syriaca.org" should be listed as publisher in any case, and my preference is to add Vanderbilt as a recognizable academic authority even though this makes the citation slightly longer.

3. Is SBD a series or a multivolume work? I thought it was a series, though even with print publications that's a matter of interpretation (http://www.chicagomanualofstyle.org/16/ch14/ch14_sec130.html). If we are treating it as a multivolume work, then I suppose it has to appear in the footnote citation, along with editors (which are not included in Option 5 above). But if it's a series, we can opt to leave it out to save space, which is what I would vote for (http://www.chicagomanualofstyle.org/16/ch14/ch14_sec128.html). The series information would still be included in the biblio, and I would opt to also include the editors there (per http://www.chicagomanualofstyle.org/16/ch14/ch14_sec129.html) for the same reasons as no. 2 above. 

4. However, what do we do with multiple series? Does Gateway to the Saints ever get listed for Qadishe entries? (Same situation with BHSE in Gateway vs. in NHSL.) We could include it in the biblio entry, but it is getting extremely long at that point. 

5. Finally, why is there a difference above between "last modified" as in the footnote and "entry published" as in the bibliography? Shouldn't it be the same format for both?

**Comment by nathangibson** [comment]
@jedwardwalters weighed in while I was writing my monograph :-). When you say including Syriaca.org as a publisher doesn't add anything, do you mean that because it's already included in the URI? It seems to me that associating the entry/volume with the project that produced it is important for "brand recognition" (not sure what the right academic term would be), but is the URI itself and the page it leads to perhaps enough for that?

**Comment by jedwardwalters** [comment]
@nathangibson Yes, that's exactly what I was thinking. Since syriaca.org is in the URI, mentioning it again is "additional" information. Though I also see the significance of brand recognition and naming the project. Despite my opinion voiced earlier, I also found your "monograph" persuasive, particularly the short fn vs. long bib entry suggestion.

**Comment by tacarlson** [comment]
I would be troubled by including Vanderbilt as the publishing authority.  Their libraries manage the hosting, but the University in no sense authorized the publication.  (Even worse, given the suppression of "Press" in some bibliographies, some people would interpret the footnote as alleging that this work was published by Vanderbilt University Press, which is factually inaccurate.)  Syriaca.org is the authorizing body (i.e. us), and anyone who wants to know who's responsible for the publication can look up the editorial list to evaluate our qualifications for the assertions we're making.  But I do not know that VU central administration or VUP would appreciate being brought into the situation.  I don't think we need any authority other than Syriaca.org, but if so, VUL would be more accurate.

I appreciate Nathan's discussion of simple notes and detailed bibliographies, so I would lean toward note option 2 (except I don't know that the date "2016-" adds anything) and Nathan's complex bibliography example (except with my name removed for projects for which I do not exercise editorial oversight).  In theory, "last modified" and "entry published" should diverge with edits; I'm not sure we wish to report both, however.

**Comment by davidamichelson** [comment]
Once we work this out we can figure out RDFA as well.

**Comment by davidamichelson** [comment]
@tacarlson and @wsalesky We discussed this in the editors meeting today and reached this conclusion.

**Footnotes**
The preferred short form for footnotes will be a simple as possible (as recommended by Chicago):

Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in _Qadishe: Guide to the Syriac Saints_, last modified August 17, 2016, http://syriaca.org/person/779.

or 

Author(s), "Article," in _Work Title_, last modified date, URI.

**Bibliography**
The preferred form will be longer and more complete:
Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In _Qadishe: Guide to the Syriac Saints_, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Vol. 1 of _The Syriac Biographical Dictionary_, edited by David A. Michelson et al. Syriaca.org, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

or

Author(s). "Article." In _Work Title_, edited by Editors. Vol. X of _Series_(if applicable). Syriaca.org, date. Entry published date, URI.

Note that here we decided on Syriaca.org as the authority not Vanderbilt and that we do want to list it and the general publication year in addition to the publication data and URI.

@tacarlson Would you approve of this being changed in the Gazeteer for uniformity?

@wsalesky If Thomas agrees, would you please adjust the How to Cite this Entry of all modules?

**Comment by tacarlson** [comment]
My name is Thomas Carlson and I approve this message, er... citation format. =-)

________________________________

**Comment by wsalesky** [comment]
Thanks @tacarlson I will start work on this today.

**Comment by wsalesky** [comment]
@davidamichelson Just to make sure I'm clear. Footnotes are under the 'Sources' section and the Bibliography would be under 'How to Cite this Entry' and also the 'Preferred Citation' on the bibl page for each bibl record?

**Comment by wsalesky** [comment]
@davidamichelson Also, what would you like to see happen with the citedRange in the footnote style citation? Should it be removed?

**Comment by davidamichelson** [comment]
@wsalesky Glad you double checked, and I'm sorry to report there is a confusion here. This request is not about the "Sources" section.

Using record http://syriaca.org/person/779 as an example these changes just apply to the two citation forms that are part of "How to Cite This Entry". "Footnote" refers the form that appears first (and by itself before one expands the "Show full citation information..." "Bibliography" refers to the form that appears second (after "Show full citation information..." is expanded) and has the title "Bibliography" before it.

Thus here is the revised form we want

**Short**
How to Cite This Entry
Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in Qadishe: Guide to the Syriac Saints, last modified August 17, 2016, http://syriaca.org/person/779.
                                                                         Show full citation information...
**Long**
How to Cite This Entry
**Footnote:**
Jeanne-Nicole Mellon Saint-Laurent et al., “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ," in Qadishe: Guide to the Syriac Saints, last modified August 17, 2016, http://syriaca.org/person/779.
**Bibliography:**
Mellon Saint-Laurent, Jeanne-Nicole et al. “Theodora, Roman empress — ܡܠܟܬܐ ܬܐܘܕܘܪܐ.” In Qadishe: Guide to the Syriac Saints, edited by Jeanne-Nicole Mellon Saint-Laurent and David A. Michelson. Vol. 1 of The Syriac Biographical Dictionary, edited by David A. Michelson et al. Syriaca.org, 2016-. Entry published August 17, 2016. http://syriaca.org/person/779.

Here are a couple notes. Please add the label "Footnote" in the expanded version but not the short. On the bibliography style, please add all editors of the module but abbreviate authors to the first author name.

**Comment by wsalesky** [comment]
Ah. Okay, thanks for the clarification! That is an easier fix!

**Comment by wsalesky** [comment]
What happens when there are 2 seriesStmt? List both? ex: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1773/tei

Also, how about when there are two biblScope in a single series stmt?
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/779/tei

List both? List only the first (which is what is currently happening)

**Comment by wsalesky** [comment]
@davidamichelson I think we can close this yes?

**Comment by wsalesky** [comment]
@davidamichelson I think this has been resolved.
