### ISSUE TITLE
Compromise on boolean operators and search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#821]
@srophe/issues-only Dear colleagues, as you know I have always been the holdout wishing that the default for our search was that it assumed an \* after the string same as Google. Since I am always forgetting to add *, I wondered if we might make this addition.

When a search result returns: "X matches for Keyword" could we please add this sentence:

Search results:

2 matches for Keyword: X. You may wish to expand your search with a wildcard (*) to increase results. See advanced search [link] for more details.

Then at the top of the advanced search page we can list the allowed operators.

Also, please note there are two extra whitespaces before the period in this sentence:

```
Search results:

2 matches for Keyword: Isaac of Nin*  .
```

**Comment by wsalesky** [comment]
Would you like us to include a description of other search operators on the advanced search page as well? 

For example wild cards are * and ?
You can also use proximity operators: "aba catholicos"~2
Phrase searching: "aba catholicos"
Fuzzy searching: aba~

**Comment by wsalesky** [comment]
@davidamichelson How does this look?
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/search.html

**Comment by davidamichelson** [comment]
@wsalesky 

Here are some edits, also please make all the examples life links to the search executed on the whole data set, http://syriaca.org/search.html?q=

**Search Tips**

For best results, users are recommended to use the advanced search functions (link on "advanced search functions")

Search results can also be improved by the use of the the following special search characters:

**Wildcard Characters:**

Given the prevalence of variant spellings in names, using Wildcard Characters may help.

"?" can be inserted as a variant for any single character.

Thus a search for "G?wargis" returns results which contain either "Gewargis" or "Giwargis".

Simiarly a search for "M?r" returns results which contain either "Mar" or "Mor".

"*" can be inserted as a variant for multiple characters or a truncated word.

Thus a search for "Dayr*" returns results for "Dayr" and "Dayro" and more.

Similarly a search for "Ab*" returns results for "ʿAbdishoʿ" and "ʿAbda" and more.

Note: Because the sources we quote use a variety of transliteration formats, Syriaca.org ignores diacritics and punctuation in searching, for example use of "ʿ" is not required to find results with this diacritical mark.

**Fuzzy Search Characters**

Appending the character "~" after a word returns results for words that are close but not matches. 

Thus a search for "Aba~" returns results which contain "Aba" but also "Abi", "Saba", "Aha", and other words that are a "fuzzy" match for "Aba".

**Exact Phrase Searches**

To find an exact phrase, it should be enclosed in double quotes. For example, "ʿAbdishoʿ I" returns only one result with that exact phrase, while several results are found for the words "ʿAbdishoʿ" and "I".

**Proximity Characters**
@wsalesky  I don't think this function is working properly, shall we leave it off for now?

Appending the character "~" followed by a number allows one to search for two or more words that occur within a specified number of words.

**Comment by nathangibson** [comment]
I edited your above text @davidamichelson to fix a couple typos. Otherwise, I think it looks good.

**Comment by dlschwartz** [comment]
I agree. This looks good to me.

**Comment by nathangibson** [comment]
This is a lot of text, though. I wonder if it would be more readable in table form, such as the following (which, however, has not preserved line breaks and which still needs @wsalesky -fairy-dust-design-magic).

| Type                      | Example Search         | Example Results                                                                          | Explanation                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|---------------------------|------------------------|------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        Wildcards (? or *) | G?wargis M?r Dayr* Ab* | "Gewargis" or "Giwargis" "Mar" or "Mor" "Dayr", "Dayro", etc. "ʿAbdishoʿ", "ʿAbda", etc. | Given the prevalence of variant spellings in names, using Wildcard Characters may help. "?" can be inserted as a variant for any single character. "*" can be inserted as a variant for multiple characters or a truncated word. Note: Because the sources we quote use a variety of transliteration formats, Syriaca.org ignores diacritics and punctuation in searching; for example use of "ʿ" is not required to find results with this diacritical mark. |
|          Fuzzy Search (~) | Aba~                   | "Aba", "Abi", "Saba", "Aha", etc.                                                        | Appending the character "~" after a word returns results for words that are close but not exact matches.                                                                                                                                                                                                                                                                                                                                                      |
|         Exact Phrase ("") | "ʿAbdishoʿ I"          | "ʿAbdishoʿ I" (but not "ʿAbdishoʿ bar Bahriz")                                           | To find an exact phrase, it should be enclosed in double quotes.                                                                                                                                                                                                                                                                                                                                                                                              |
| Proximity (~ plus number) | "Jacob Bishop"~2       | "Jacob , bishop of Nisibin", "Jacob, bishop of Phesilta", and "Jacob , bishop of ‛Ānah"  | To find two or more words which occur within a specified range of each other, one can append the character "~" followed by a number to an "Exact Phrase" search. This allows one to search for two or more words that occur within a specified distance of each other as defined by number of words.                                                                                                                                                          |

**Comment by dlschwartz** [comment]
Ohhh, I like the table even better!

**Comment by davidamichelson** [comment]
Sorry, I fell very strongly opposed to the table. The point of this help is to be accessible to non-tech scholars who are used to prose and text criticism but have never even met the concept of wildcard characters befoire. I think the table will not be intuitive for them because it starts with the characters rather than the purpose.

**Comment by nathangibson** [comment]
Well, I can understand that. It is a lot of text, though. What about adding a bit of extra formatting to the prose to make it easier to skim. For example, putting the relevant characters in parentheses after the bold headers, and labeling the examples clearly with **Example: ** or something?

**Comment by davidamichelson** [comment]
That would be fine, in fact I had not intended the prose here to be fully styled, please make it beautiful @wsalesky

**Comment by davidamichelson** [comment]
Also the quotation marks will be need special handling since sometimes they are part of the actual search string

**Comment by wsalesky** [comment]
First attempt is up on dev (any search page). It is quite wordy, which requires scrolling. I could add collapsible sections to make it more compact with slightly less scrolling. Let me know what you think.

**Comment by nathangibson** [comment]
Looks good to me. Did we purposely leave out "Proximity Characters"?

**Comment by wsalesky** [comment]
Nope, that was an inadvertent edit. I will add them back in.

**Comment by nathangibson** [comment]
FWIW, I think the formatting looks good now. Not sure that it's such a terrible thing to have to scroll either.

**Comment by wsalesky** [comment]
Thanks. I dislike the scrolling, but I think I will let it go.

**Comment by davidamichelson** [comment]
Okay, a few thoughts on this.

1. Maybe these helps should just be a documentation page for each module then the scrolling would be natural? We can discuss briefly today.

2. I like how each pop up has a link to "advanced search" that is module specific. Let's discuss which modules the examples should search.

**Comment by davidamichelson** [comment]
Please ignore 1 and 2 above. Instead make the box a toggle. And please push to production.

**Comment by wsalesky** [comment]
Here is an example with the show/hide rather then the popup:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/authors/search.html

Let me know if you have a preference.
