### ISSUE TITLE
Need better label for advanced search features in corner box

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#864]
Please make this a priority for this week.

**Comment by wsalesky** [comment]
@davidamichelson,  how does this look:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

**Comment by davidamichelson** [comment]
I think it is still too opaque. Maybe instead of "Advanced" it could say "Search Tools"?

**Comment by wsalesky** [comment]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

**Comment by davidamichelson** [comment]
I like it. I'd like to expedite getting this to the production server. Let me poll the editors. @tacarlson, this will affect the Gazetteer as well if you approve.

**Comment by nathangibson** [comment]
+1

**Comment by davidamichelson** [comment]
Unless there are any objections at our meeting today, I am approving this change of label. Please deploy to all modules and push to production.

@tacarlson I'm assuming silence means you find this amenable. Please know your input is welcome.

**Comment by davidamichelson** [comment]
Could we add this label to the boxes on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/saints/index.html please?

**Comment by wsalesky** [comment]
Yes, I will go through and add it to all the pages with the 'advanced search widget.'

**Comment by tacarlson** [comment]
This looks fine, although my preference would be to capitalize the mouse-over text "advanced search."  But I do not regard that as a sine qua non, if there is a reason to prefer it uncapitalized.

As it turns out, silence just means that I judged the issue title to have nothing to do with the Gazetteer.  Mentions of my user-name in issue comments are ineffective at reaching me because I am already following the repository; if you need my input, please email me directly or email the editors, rather than relying on GitHub's @ mentions which do not generate any additional signal in my stream.

**Comment by wsalesky** [comment]
Resolved via: https://github.com/srophe/srophe-eXist-app/commit/bd0be5dfd946815868bd06253c4a9fcf673775fa
