### ISSUE TITLE
Advanced Search in Gazetteer Place Name returns results that it should not.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#874]
A search for "Abd*" in Gazetteer> Advanced Search>Place Name: returns results that it should not.

I believe this is due to a mistaken x-path in the search.

See:

http://syriaca.org/geo/search.html?q=&p=Abd*&loc=&e=&eds=&ede=&a=&ads=&ade=&c=&cds=&cde=&existds=&existde=&type=

Mistaken Results include:
http://syriaca.org/place/217.html

Note that this record has no tei:body/listPlace/placeName that contains the string "abd*" but it does have a tei:body/listPlace/desc/placeName that does. This is not the correct path for this search however.

For the Gazetteer, search by "Place Name" should only search in the direct path: tei:body/listPlace/placeName

For SBD and BHSE, search by Person Name or Title  does work correctly using an analogous path e.g. tei:body/listPerson/persName 

@tacarlson I assume we would want to push the fix for this to production?

**Comment by wsalesky** [comment]
This is not a xquery bug, it is in the xml:
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/217.xml#L105
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/217.xml#L106

Are these names a mistake?

**Comment by tacarlson** [comment]
Yes, these names are a mistake, evidently derived from the `<placename>` on https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/217.xml#L107 by the earlier process which had inserted simplified Syriac names.

Any ideas on scripts to detect all syriaca-simplified-script names which were *not* derived from a tei:TEI/body/listPlace/place/placeName but from some other placeName?  (Notice insertion of 'place' into the path DAM suggested.)

**Comment by wsalesky** [comment]
Yes, I will write a script to find all the added names and then check them against the correct placeNames (id, only the ones that are the direct child of tei:place) I will make a list of the problem records so they can be reviewed before I make any changes.

**Comment by wsalesky** [comment]
I found 10 records:
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/89.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/665.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/97.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/1502.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/1948.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/167.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/164.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/516.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/511.xml
https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/429.xml

Let me know if you would like me to make the changes. I can do it today.

**Comment by wsalesky** [comment]
Fix script and rerun on dev data.

**Comment by davidamichelson** [comment]
Script originally written on Nov 2014

**Comment by tacarlson** [comment]
I did not notice this thread last month, but I think there are greater issues here which need to be discussed, which were surfaced by my review of the results of a different recent change.  Please do not simply rerun script on dev data until the editors can discuss this issue.

**Comment by dlschwartz** [comment]
@tacarlson We discussed this issue at the meeting today. The course of action we settled on was to delete the results of the old script, fix the script, text that it is working correctly, and run it again. Please let us know if you think there is some reason that this is a problematic course of action. Thanks.

**Comment by tacarlson** [comment]
I was not present at the meeting today and have a few remaining questions.  I will email you directly about those shortly.

**Comment by tacarlson** [comment]
Among other things, the list of problem records given in https://github.com/srophe/srophe-eXist-app/issues/874#issuecomment-258883870 is incomplete.

**Comment by wsalesky** [comment]
I have found and fixed the bug in the script. I will rerun this on the dev data (in a new branch) and let the editors review to make sure it does indeed fix the error. The script was not restricting to direct children of the tei:place element, so it was also providing alternate names for placeNames within the tei:desc element.

**Comment by wsalesky** [comment]
Changes to places data are on this branch:
https://github.com/srophe/srophe-app-data/tree/issueApp874

**Comment by davidamichelson** [comment]
Hi W I think we would like to review the script first can you post it please?

Thanks

**Comment by wsalesky** [comment]
Yes, the script is here:
https://github.com/srophe/srophe-xQueries/blob/master/alt-names-placeName.xql

**Comment by tacarlson** [comment]
I have a few questions about the asymmetries between the two main functions of the script (xQuery is unfamiliar to me), and I found a number of remaining issues which should probably be discussed, I suspect, before further effort is put into this script:

1. This script does not work as expected on records which have been edited since an earlier run of this script (e.g. clashing name xml-ids of https://github.com/srophe/srophe-app-data/blob/issueApp874/data/places/tei/198.xml#L122-L130 ).  In particular, the script seems to presume that the number of `<placeName>` elements is the same as the highest number in a name xml:id attribute, and therefore rather than parsing the highest name xml:id, it increments the number of `<placeName>` elements by one and uses this.  But this fails when earlier place names have been deleted from the middle of the range, which is what happened when we deleted the earlier simplified place names after having added new place names subsequent them.  This may be unique to this record (a script identifying if any record has duplicate xml:ids would detect it), but this may be a problem with the desired use-case in item 3 below.  Alternately, it might be solved by not assigning xml:ids to simplified names, but this would require a discussion to determine possible implications of this approach.

2. https://github.com/srophe/srophe-app-data/blob/issueApp874/data/places/tei/1857.xml has two identical place names "Malakā Gabriel" because the simplification procedure produced what is also attested in a secondary source.  It would be better, I think, for us not to include "simplified" names alongside attested names.

3. Relatedly, @davidamichelson elsewhere expressed to me a desire to have a script which could be run after any manual edit of data records, so that a human is not attempting to imitate the behavior of the script by hand.  This, of course, would require detecting and not duplicating place name xml:ids (nor, ideally, place names) during the simplification process.  It would also need to be written in an environment which I would be able to run.

4. A desired behavior for the module editors to discuss: removing these erroneous simplified place names will have the effect that searching for simplified strings (e.g. "Tur Abdin") will miss records which have the precisely transcribed string in subordinate elements (e.g. https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/238.xml which has "Ṭur ʿAbdin" in its `<desc>` but no occurrence of the string "Tur Abdin" anywhere in the record).  We cannot assert that "Tur Abdin" is a `<placeName>` of place/238, but is there some other location within the record to add "Tur Abdin" as a keyword, so that this record may be retrieved if someone searches for this?  Or is there some other method to achieve this behavior?  Can we perhaps leverage RDF asserting "synonyms" in a search process?

**Comment by davidamichelson** [comment]
@tacarlson in preparation for discussing this issue, if time permits, I have reviewed the script posted here. In abbreviated terms, the script does the following (@wsalesky please let me know if I am mistaken):

The script identifies place names which contain left-half ring and only at this level/path place/placeName (thus placeNames which are not the direct child of a tei:place but in a tei:note/@type="abstract" would not be affected). I think we might even want to specify this path more strictly to be place[1]/placeName but perhaps that is not necessary since tei:place occurs in only one path in our schema.

The script then adds two new place/placeNames/@xml:lang="en-x-srp1" which mirror the selected name but replacing the left-ring character with nothing and with an apostrophe. Note: might we want to add: ʕ, U+0295?

The script then repeats this for right-ring replacing it with nothing. Note: might we want to add a superscript 'c' or some other punctuation?

Finally it adds a note to the revisionDesc about the new names.

**Comment by davidamichelson** [comment]
At the 1/24/17 developers meeting we reviewed the 4 items listed by @tacarlson above and reached the following agreements. @wsalesky would you please read both these comments here and refer to the post by @tacarlson above for reference.

"1. This script does not work as expected on records which have been edited since an earlier run of this script..."

There are a couple of issues here.

First, the way that new xml-ids are created can cause a conflict where two placeNames would have the same xml-id. This is because the xQuery calculates the new xml-id using count. Count will not work in a scenario in which a placeName has been deleted. For example if a record has two placeNames with xml-ids of name78-1 and name78-3, the new script would create a new name and name it also name78-3. We are considering a couple of solutions to this and I will post the preferred version shortly.

A related issue is how to handle running the script on data in which the script has already been run previously. There is risk that the sequencing of the xml-ids could get disjointed or numerically high through repeated running.

"2.  https://github.com/srophe/srophe-app-data/blob/issueApp874/data/places/tei/1857.xml has two identical place names..."

On this item we determined that it would be good for the script to include a test. If the new name generated by the script matches as a string the string on any existing name then the new name should not be inserted. @wsalesky Please let me know if this needs clarification.

"3. Relatedly, @davidamichelson elsewhere expressed to me a desire to have a script which could be run after any manual edit of data records..."

We agree tentatively that ideally these maintenance scripts would be run in connection with finalization of a record in Perseids. A separate issue will be filed on this.

"4. A desired behavior for the module editors to discuss..."

On this item we determined that while the desired search results describe here were ideal it would be overly cumbersome to add the simplified script names in any locations other than the core naming section for each record, e.g. body/place[1]/placeName or body/person[1]/persName or the equivalent in NSHL. (@ngibson what is the equivalent?). We agreed to look into great use of URIs in abstracts and to encouraging users to use URIs in search.

**Comment by davidamichelson** [comment]
@wsalesky for now please make the change for number 2 above and I will post about number 1 when ready

**Comment by davidamichelson** [comment]
oops I forgot one item related to numbers 1 and 3 above. @wsalesky We would like to have script delete all previously generated simplified names each time it runs. Could you please add a delete that removes all names based on the "en-x-srp1" tag before running the script. This will prevent duplicates and also help deleted orphaned simplified names whose source name may have changed or been deleted.

**Comment by davidamichelson** [comment]
Okay, here is a resolution on xml-id generation:

Please have the script derive the new placeName's xml-id  from the xml-id of its source placeName.

Thus:
 ```<placeName xml:id="name221-1" xml:lang="en" syriaca-tags="#syriaca-headword" source="#bib221-2">Ṭur ʿAbdin</placeName>```
                    
produces
                    ```<placeName xml:id=“name221-1a" xml:lang="en-x-srp1" syriaca-tags="#syriaca-simplified-script">Ṭur Abdin</placeName>
                    <placeName xml:id=“name221-1b" xml:lang="en-x-srp1" syriaca-tags="#syriaca-simplified-script">Ṭur ‘Abdin</placeName>```

This has the advantage of being guaranteed to be unique and also conveying information about the source of the new simplified names.

@wsalesky For laughs please do a quick search to make sure that we are not using 1a somewhere already! If so we need to manually change those records.

Also, a further thought from @tacarlson who points out that the string test for whether the simplified name' string is already encoded in the record should prevent duplicates when the script is re-run.

It may be, however, that we still should delete all  "en-x-srp1" names each time the script runs because we would want to remove orphaned names whose source is no longer in the record.

**Comment by wsalesky** [comment]
A far as I can tell the new numbering for xml:ids is only used in bibls:
ex:
```
<bibl xmlns="http://www.tei-c.org/ns/1.0" xml:id="bib680-2b" type="lawd:Citation">
   <title xml:lang="en" level="m">The Greek Text Edited with Introduction and Notes</title>
   <title xml:lang="en" level="s">Texts and Studies</title>
   <title xml:lang="en" level="m">The Lausiac History of Palladius</title>
   <ptr target="http://syriaca.org/bibl/1208"/>
   <citedRange unit="pp">lxxvii-lxxx</citedRange>
</bibl>
```

**Comment by wsalesky** [comment]
For future records, this has been handled by the update scripts, integrated into the Perseids approval process (https://github.com/srophe/srophe-eXist-app/issues/935). Do we need to run an update on existing records as well? @davidamichelson

**Comment by wsalesky** [comment]
This has been resolved.
