### ISSUE TITLE
Maps for SBD home page

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#890]
Add maps for persons. Add related persons to popup.

**Comment by wsalesky** [comment]
Added map. 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

We can review before pushing to production.

**Comment by wsalesky** [comment]
Not sure about the placement of the map, as it pushes all the content way down the page. We could move it to the right column, or move it elsewhere.

**Comment by wsalesky** [comment]
Another options for map placement:
http://wwwb.library.vanderbilt.edu/persons/index.html

**Comment by wsalesky** [comment]
@davidamichelson What do you think about this version of the maps on the persons home page?

**Comment by wsalesky** [comment]
@davidamichelson @dlschwartz @nathangibson @jsaintlauren 
What do you think of this for SBD home page layout?
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/index.html

Thanks!

**Comment by nathangibson** [comment]
I like this. The map is big enough to see but doesn't dominate. And linking to a larger map is helpful. 

I wonder, though, would we want to simply put the introduction inline below rather than linking to a separate "about" page?

**Comment by wsalesky** [comment]
@nathangibson @jsaintlauren  @davidamichelson @dlschwartz 
Okay, fixed map on persons browse page and added a map tab to SBD, Authors and Q. Let me know if you are ready to have it on production. 
-Winona

**Comment by nathangibson** [comment]
Looking great to me! I especially like the map on advanced browse that dynamically updates based on criteria, e.g., 4th century Syriac saints: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?fq=;fq-Type:http://syriaca.org/q;fq-Century:300-400&view=facets.

**Comment by dlschwartz** [comment]
Agreed, this is looking really good.

**Comment by jsaintlauren** [comment]
I LOVE it!!

**Comment by davidamichelson** [comment]
Please change "* 131 have coordinates and are shown on this map. " to:

"This map only plots places with coordinates in the Syriac Gazetteer. See FAQ..."

**Comment by davidamichelson** [comment]
@wsalesky made a slight change.

**Comment by tacarlson** [comment]
I just received a notice about this issue via email, and I would like time to review this before pushing to  production, ideally while I am not traveling internationally for a conference.  However, it is not clear from my brief perusal of the foregoing discussion what link I should be perusing.  Might someone mind providing a summary of what changes (including to the Gazetteer) are being considered for production, and why?  I would also be interested in seeing a case why this change to the SBD home page should affect the Gazetteer.  Thanks!

**Comment by davidamichelson** [comment]
@tacarlson That is, of course acceptable, @wsalesky let's hold off on pushing this to production for now.

**Comment by wsalesky** [comment]
Sounds good. I will hold off on this one.

**Comment by tacarlson** [comment]
I have looked over the proposed change.  I agree that the current map caveat text could usefully be clarified.  As Dave knows from a long string of earlier conversations, I think the map caveat text is critically important to the intellectual integrity of the Gazetteer, for avoiding the seductive obscurity of a bare map which does not make clear what is being mapped.  Unfortunately, the proposed new text is static, which removes an important function: the ability to evaluate individual maps differentially (since it would be the same text if 8 out of 100 or 98 out of 100 places had coordinates).  This is, to my mind, the necessary function of the caveat text, and so I am opposed to replacing dynamic text with any static text.  Instead, I would suggest that we revise the dynamic text for clarity, but keep it dynamic, at least for the Gazetteer.  Perhaps "This map displays only those places (X out of Y total) which have coordinates recorded in the Gazetteer"?  I welcome alternate suggestions.

You are welcome to do what you like with the other modules, of course.

**Comment by wsalesky** [comment]
@tacarlson thank you for the feed back. I will fix the dynamic function on the dev server first and we can review it.

**Comment by davidamichelson** [comment]
@wsalesky could you please push this to the development server:

“This map displays X of Y places. Only places with coordinates in The Syriac Gazetteer are displayed. [See why?]” See why links to the FAQ as a present.

Also, could you please add a title above the map. Title should be “Related places.” This should be static and part of the frame rather than the function and may vary by instance but for now please put on all instances of this map in SBD only.

In the Gazetteer please leave off the title.

Please push to dev and let us know so we can review.

**Comment by wsalesky** [comment]
@davidamichelson Ready for review.

**Comment by davidamichelson** [comment]
I love it. Could the "Related Places" map title be added elsewhere in SBD please such as here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?fq=;fq-Type:http://syriaca.org/q;fq-Century:300-400&view=facets

**Comment by wsalesky** [comment]
Sure. How does this look: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?fq=;fq-Type:http://syriaca.org/q;fq-Century:300-400&view=facets

**Comment by davidamichelson** [comment]
Great!

**Comment by tacarlson** [comment]
It looks like there are now map titles across SBD, but the map caveat has not been updated on http://syriaca.org/person/50 or other person records.  The caveat should be made consistent across all modules, pending agreement by the other module editors.

________________________________

**Comment by wsalesky** [comment]
Thanks @tacarlson I missed that map. Here it is: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/50

**Comment by dlschwartz** [comment]
This looks great! Thanks Winona.

**Comment by wsalesky** [comment]
Maps for SBD are now on production.

**Comment by jsaintlauren** [comment]
Looks great!!
